name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build APK using Buildozer Docker Image
      uses: addnab/docker-run-action@v3
      with:
        image: kivy/buildozer:latest
        options: -v ${{ github.workspace }}:/home/user/hostroot
        run: |
          yes | buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Android-APK
        path: bin/*.apk
        
